name: pingpal
description: A mobile cloud computing friend location app with adaptive caching.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.2
  cherry_toast: ^1.13.0
  share_plus: ^12.0.1

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.2.1

  # Maps + Location
  geolocator: ^13.0.1
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.14.0

  # REST API
  http: ^1.2.2

  # State management
  provider: ^6.1.2
  font_awesome_flutter: ^10.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

package_rename_config:
  android:
    app_name: Pingpal
    package_name: com.example.pingpal
    override_old_package:
    lang: java

  ios:
    app_name: Pingpal
    bundle_name:
    package_name:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
